name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Instalar deps
        run: npm ci --silent
      - name: Instalar Playwright (Chromium + deps)
        run: npx playwright install --with-deps chromium
      - name: Build extensão
        run: npm run build
      - name: Testes E2E
        run: npm run test:e2e || npm run test:e2e -- --reporter=html
      - name: Publicar relatório do Playwright
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
      - name: Publicar pacote da extensão (.zip)
        uses: actions/upload-artifact@v4
        with:
          name: extension-zip
          path: dist/extension.zip
