name: CI

on:
  workflow_dispatch:          # permite rodar manualmente
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest

    env:
      PROJECT_DIR: my-chrome-extension/my-chrome-extension

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ${{ env.PROJECT_DIR }}/package-lock.json

      - name: Diagnóstico (onde estamos e o que existe)
        run: |
          echo "PWD (raiz do repo):"; pwd
          echo "Listando raiz:"
          ls -la
          echo "Entrando no projeto: $PROJECT_DIR"
          cd "$PROJECT_DIR"
          echo "PWD do projeto:"; pwd
          echo "Listando o projeto:"
          ls -la
          echo "Mostrando package.json:"
          cat package.json || true

      - name: Instalar dependências
        working-directory: ${{ env.PROJECT_DIR }}
        run: npm install --no-audit --no-fund --silent

      - name: Instalar Playwright (Chromium + deps)
        working-directory: ${{ env.PROJECT_DIR }}
        run: npx playwright install --with-deps chromium

      - name: Build (gera dist/ e dist/extension.zip)
        working-directory: ${{ env.PROJECT_DIR }}
        run: npm run build

      - name: Testes E2E (gera relatório HTML)
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          npx playwright test --reporter=html || echo "::warning:: testes falharam; publicaremos artefatos mesmo assim"
        continue-on-error: true

      - name: Publicar relatório do Playwright
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ${{ env.PROJECT_DIR }}/playwright-report

      - name: Publicar pacote da extensão (.zip)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extension-zip
          path: ${{ env.PROJECT_DIR }}/dist/extension.zip
